services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      -
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      -
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=
    depends_on:
      - prometheus