create user vuelos identified by vuelos default tablespace USERS temporary tablespace TEMP;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE SYNONYM, CREATE PROCEDURE, CREATE TRIGGER 
TO vuelos;
ALTER USER vuelos QUOTA UNLIMITED ON USERS;
CONNECT vuelos/vuelos;
-- =========================
-- AEROPUERTO
-- =========================
CREATE TABLE aeropuerto (
  id_aeropuerto       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre              VARCHAR2(100) NOT NULL,
  localidad           VARCHAR2(100) NOT NULL,
  pais                VARCHAR2(100) NOT NULL,
  CONSTRAINT pk_aeropuerto PRIMARY KEY (id_aeropuerto)
);

-- =========================
-- AVION
-- =========================
CREATE TABLE avion (
  id_avion            NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo_avion        VARCHAR2(50) NOT NULL,
  num_plazas          NUMBER(5) NOT NULL,
  tipo_de_avion       VARCHAR2(50) NOT NULL,
  CONSTRAINT pk_avion PRIMARY KEY (id_avion)
);

-- =========================
-- PERSONAS (clientes)
-- =========================
CREATE TABLE personas (
  id_persona          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dni                 VARCHAR2(30) NOT NULL,
  nombre              VARCHAR2(100) NOT NULL,
  direccion           VARCHAR2(200),
  telefono            VARCHAR2(30),
  CONSTRAINT pk_personas PRIMARY KEY (id_persona)
);

-- =========================
-- TARJETA_DE_CREDITO (1-N con PERSONAS)
-- =========================
CREATE TABLE tarjeta_credito (
  id_tarjeta          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_persona          NUMBER(10) NOT NULL,
  procesador_de_pago  VARCHAR2(40) NOT NULL,
  ultimos_dos_digitos VARCHAR2(2) NOT NULL,
  mes_vigencia        NUMBER(2) NOT NULL,
  anio_vigencia       NUMBER(4)NOT NULL,
  CONSTRAINT pk_tarjeta_credito PRIMARY KEY (id_tarjeta),
  CONSTRAINT fk_tc_persona FOREIGN KEY (id_persona)
    REFERENCES personas (id_persona)
);

-- =========================
-- VUELOS (cada vuelo lo realiza un avión y tiene aeropuertos origen/destino)
-- =========================
CREATE TABLE vuelos (
  id_vuelo                NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo_de_vuelo         VARCHAR2(20) NOT NULL,      
  fecha_salida            VARCHAR2(20) NOT NULL,
  fecha_llegada           VARCHAR2(20) NOT NULL,
  id_avion                NUMBER(10) NOT NULL,
  id_aeropuerto_origen    NUMBER(10) NOT NULL,
  id_aeropuerto_destino   NUMBER(10) NOT NULL,
  origen                  VARCHAR2(100) NOT NULL,
  destino                 VARCHAR2(100) NOT NULL,
  CONSTRAINT pk_vuelos PRIMARY KEY (id_vuelo),
  CONSTRAINT fk_vuelos_avion FOREIGN KEY (id_avion)
    REFERENCES avion (id_avion),
  CONSTRAINT fk_vuelos_aerop_origen FOREIGN KEY (id_aeropuerto_origen)
    REFERENCES aeropuerto (id_aeropuerto),
  CONSTRAINT fk_vuelos_aerop_dest FOREIGN KEY (id_aeropuerto_destino)
    REFERENCES aeropuerto (id_aeropuerto)
);

-- =========================
-- RESERVA (la hace una persona, para un vuelo, y con cantidad de plazas)
-- =========================
CREATE TABLE reserva (
  id_reserva          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_persona          NUMBER(10) NOT NULL,  
  id_vuelo            NUMBER(10) NOT NULL,
  cantidad            NUMBER(5) NOT NULL,
  fecha_reserva       VARCHAR2(20)  NOT NULL,
  CONSTRAINT pk_reserva PRIMARY KEY (id_reserva),
  CONSTRAINT fk_reserva_persona FOREIGN KEY (id_persona)
    REFERENCES personas (id_persona),
  CONSTRAINT fk_reserva_vuelo FOREIGN KEY (id_vuelo)
    REFERENCES vuelos (id_vuelo)
);

-- =========================
-- PASAJERO (vincula persona con una reserva específica)
-- Cada persona que viaja dentro de una reserva queda aquí.
-- =========================
CREATE TABLE pasajero (
  id_pasajero         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_reserva          NUMBER(10) NOT NULL,
  id_persona          NUMBER(10) NOT NULL, 
  CONSTRAINT pk_pasajero PRIMARY KEY (id_pasajero),
  CONSTRAINT fk_pasajero_reserva FOREIGN KEY (id_reserva)
    REFERENCES reserva (id_reserva),
  CONSTRAINT fk_pasajero_persona FOREIGN KEY (id_persona)
    REFERENCES personas (id_persona)
);

-- =========================
-- ASIENTOS (definidos por vuelo y su ubicación física)
-- Se modela con surrogate key y unicidad por (vuelo, fila, columna, planta)
-- =========================
CREATE TABLE asientos (
  id_asiento          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  fila                NUMBER(3)  NOT NULL,
  columna             VARCHAR2(3) NOT NULL,  
  planta              NUMBER(2) NOT NULL,
  id_vuelo            NUMBER(10) NOT NULL,
  CONSTRAINT pk_asientos PRIMARY KEY (id_asiento),
  CONSTRAINT fk_asientos_vuelo FOREIGN KEY (id_vuelo)
    REFERENCES vuelos (id_vuelo)
);

-- =========================
-- TARJETA_EMBARQUE (puede existir sin reserva; siempre 1 pasajero/1 asiento)
-- =========================
CREATE TABLE tarjeta_embarque (
  id_embarque         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_persona          NUMBER(10),
  id_pasajero         NUMBER(10),
  fecha_de_embarque   VARCHAR2(20)  NOT NULL,
  id_vuelo            NUMBER(10) NOT NULL,  
  id_asiento          NUMBER(10) NOT NULL,  
  CONSTRAINT pk_tarjeta_embarque PRIMARY KEY (id_embarque),
  CONSTRAINT fk_te_persona FOREIGN KEY (id_persona)
    REFERENCES personas (id_persona),
  CONSTRAINT fk_te_pasajero FOREIGN KEY (id_pasajero)
    REFERENCES pasajero (id_pasajero),
  CONSTRAINT fk_te_vuelo FOREIGN KEY (id_vuelo)
    REFERENCES vuelos (id_vuelo),
  CONSTRAINT fk_te_asiento FOREIGN KEY (id_asiento)
    REFERENCES asientos (id_asiento)
);

